name: enven
description: Generate environment variables from a .env file at compile time with optional obfuscation.
version: 1.2.1
repository: https://github.com/Tienisto/enven
topics:
  - env
  - dotenv
  - token
  - encryption
  - obfuscation
funding:
  - https://github.com/sponsors/Tienisto/

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  build: ^2.1.0

dev_dependencies:
  lints: any
  test: any
